import { useState } from 'react';

const ontologyNodes = [
  { id: 'AssetInstance', label: 'owl:Class · AssetInstance', group: 'Physical', color: '#00c8ff', comment: 'Physical hardware inventory. The top record is the tail number (BUNO) itself.', properties: ['partUuid ➔ PartCatalog', 'parentAssetUuid ➔ AssetInstance'] },
  { id: 'PartCatalog', label: 'owl:Class · PartCatalog', group: 'Physical', color: '#00c8ff', comment: 'Master catalog containing engineering specifications from tail to wash/screws.', properties: ['nhaPartUuid ➔ PartCatalog'] },
  { id: 'TriggeredFaultLog', label: 'owl:Class · TriggeredFaultLog', group: 'Sensing', color: '#ff6b35', comment: 'Machine-generated telemetry log of when a built-in-test (BIT) code goes active.', properties: ['aircraftAssetUuid ➔ AssetInstance', 'faultCodeUuid ➔ FaultCodeMaster'] },
  { id: 'ConditionIndicatorLog', label: 'owl:Class · ConditionIndicatorLog', group: 'Sensing', color: '#ff6b35', comment: 'Telemetry metrics and RMS vibration/temperature values extracted from flight sensors.', properties: ['sensorUuid ➔ SensorCatalog', 'assetUuid ➔ AssetInstance'] },
  { id: 'CbmPredictiveAlert', label: 'owl:Class · CbmPredictiveAlert', group: 'Comparator', color: '#39ff7a', comment: 'Proactive failure predictions generated by machine learning models.', properties: ['assetUuid ➔ AssetInstance', 'predictedFailureModeUuid ➔ FmeaFailureMode'] },
  { id: 'AmisModelInference', label: 'owl:Class · AmisModelInference', group: 'Decision', color: '#c77dff', comment: 'Machine diagnoses and confidence ratings generated by AMIS logic.', properties: ['discrepancyUuid ➔ MaintenanceDiscrepancy', 'recommendedPartUuid ➔ PartCatalog'] },
  { id: 'SmeOverrideReport', label: 'owl:Class · SmeOverrideReport', group: 'Meta', color: '#ff4da6', comment: 'Second-order feedback report logging SME/engineer overrides of AI predictions.', properties: ['inferenceUuid ➔ AmisModelInference', 'smeUuid ➔ Maintainer'] },
  { id: 'CyberneticFeedbackLoop', label: 'owl:Class · CyberneticFeedbackLoop', group: 'Meta', color: '#ff4da6', comment: 'Cybernetic loop ledger tracking prediction error rates and adaptation decisions.', properties: ['discrepancyUuid ➔ MaintenanceDiscrepancy', 'actionUuid ➔ MaintenanceAction'] },
];

export default function Tab17OntologyMap() {
  const [selectedNodeId, setSelectedNodeId] = useState('CyberneticFeedbackLoop');

  const selectedNode = ontologyNodes.find(n => n.id === selectedNodeId) || ontologyNodes[0];

  return (
    <div className="p-4 space-y-6 overflow-y-auto h-full bg-amis-bg">
      <div>
        <h1 className="text-sm font-bold text-amis-text-bright tracking-widest uppercase">OWL Ontology Map</h1>
        <p className="text-xs text-amis-text-dim mt-1">Layer 1 · Physical · Semantic knowledge map, class relationships, and semantic data models from Amis_public.owl</p>
      </div>

      <div className="p-4 border border-amis-l6/40 bg-amis-l6/5 rounded text-xs text-amis-text leading-relaxed">
        <span className="text-amis-l6 font-bold uppercase tracking-wider block mb-1">ONTOLOGY EXPLAINER</span>
        Relational databases represent raw transactions. The **OWL Ontology** represents the *meaning* (semantics) of those transactions. 
        AMIS uses this semantic model to link telemetry anomalies directly to tech manuals and logistics, enabling ARIA to answer context-aware questions.
        **Click on any node** below to inspect its semantic properties and constraints.
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* ONTOLOGY GRAPH SVG */}
        <div className="lg:col-span-2 bg-amis-panel border border-amis-border rounded p-4 flex flex-col items-center justify-center min-h-[400px]">
          <svg viewBox="0 0 700 400" className="w-full max-w-[600px] h-auto">
            {/* Draw lines representing semantic relationships */}
            <defs>
              <marker id="arrow" viewBox="0 0 10 10" refX="18" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
                <path d="M 0 0 L 10 5 L 0 10 z" fill="#1a2a40" />
              </marker>
              <marker id="arrow-active" viewBox="0 0 10 10" refX="18" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
                <path d="M 0 0 L 10 5 L 0 10 z" fill="#ff4da6" />
              </marker>
            </defs>

            {/* AssetInstance -> PartCatalog */}
            <line x1="150" y1="120" x2="150" y2="280" stroke={selectedNodeId === 'AssetInstance' ? '#ff4da6' : '#1a2a40'} strokeWidth="1.5" markerEnd="url(#arrow)" />
            <text x="110" y="200" fill="#5a7a9a" fontSize="8" fontFamily="monospace">partUuid</text>

            {/* TriggeredFaultLog -> AssetInstance */}
            <line x1="330" y1="80" x2="200" y2="105" stroke={selectedNodeId === 'TriggeredFaultLog' ? '#ff4da6' : '#1a2a40'} strokeWidth="1.5" markerEnd="url(#arrow)" />

            {/* ConditionIndicatorLog -> AssetInstance */}
            <line x1="330" y1="180" x2="200" y2="135" stroke={selectedNodeId === 'ConditionIndicatorLog' ? '#ff4da6' : '#1a2a40'} strokeWidth="1.5" markerEnd="url(#arrow)" />

            {/* CbmPredictiveAlert -> AssetInstance */}
            <line x1="500" y1="120" x2="200" y2="120" stroke={selectedNodeId === 'CbmPredictiveAlert' ? '#ff4da6' : '#1a2a40'} strokeWidth="1.5" markerEnd="url(#arrow)" />

            {/* AmisModelInference -> CbmPredictiveAlert */}
            <line x1="500" y1="260" x2="500" y2="140" stroke={selectedNodeId === 'AmisModelInference' ? '#ff4da6' : '#1a2a40'} strokeWidth="1.5" markerEnd="url(#arrow)" />

            {/* SmeOverrideReport -> AmisModelInference */}
            <line x1="350" y1="310" x2="450" y2="290" stroke={selectedNodeId === 'SmeOverrideReport' ? '#ff4da6' : '#1a2a40'} strokeWidth="1.5" markerEnd="url(#arrow)" />

            {/* CyberneticFeedbackLoop -> AmisModelInference */}
            <line x1="500" y1="360" x2="500" y2="300" stroke={selectedNodeId === 'CyberneticFeedbackLoop' ? '#ff4da6' : '#1a2a40'} strokeWidth="1.5" markerEnd="url(#arrow)" />

            {/* NODES */}
            {/* AssetInstance */}
            <g className="cursor-pointer" onClick={() => setSelectedNodeId('AssetInstance')}>
              <circle cx="150" cy="120" r="25" fill="#0b1120" stroke={selectedNodeId === 'AssetInstance' ? '#ff4da6' : '#00c8ff'} strokeWidth="2" />
              <text x="150" y="123" textAnchor="middle" fill="#dceeff" fontSize="9" fontWeight="bold">Asset</text>
            </g>

            {/* PartCatalog */}
            <g className="cursor-pointer" onClick={() => setSelectedNodeId('PartCatalog')}>
              <circle cx="150" cy="280" r="25" fill="#0b1120" stroke={selectedNodeId === 'PartCatalog' ? '#ff4da6' : '#00c8ff'} strokeWidth="2" />
              <text x="150" y="283" textAnchor="middle" fill="#dceeff" fontSize="9" fontWeight="bold">Catalog</text>
            </g>

            {/* TriggeredFaultLog */}
            <g className="cursor-pointer" onClick={() => setSelectedNodeId('TriggeredFaultLog')}>
              <circle cx="350" cy="80" r="25" fill="#0b1120" stroke={selectedNodeId === 'TriggeredFaultLog' ? '#ff4da6' : '#ff6b35'} strokeWidth="2" />
              <text x="350" y="83" textAnchor="middle" fill="#dceeff" fontSize="9" fontWeight="bold">Fault</text>
            </g>

            {/* ConditionIndicatorLog */}
            <g className="cursor-pointer" onClick={() => setSelectedNodeId('ConditionIndicatorLog')}>
              <circle cx="350" cy="180" r="25" fill="#0b1120" stroke={selectedNodeId === 'ConditionIndicatorLog' ? '#ff4da6' : '#ff6b35'} strokeWidth="2" />
              <text x="350" y="183" textAnchor="middle" fill="#dceeff" fontSize="9" fontWeight="bold">Telemetry</text>
            </g>

            {/* CbmPredictiveAlert */}
            <g className="cursor-pointer" onClick={() => setSelectedNodeId('CbmPredictiveAlert')}>
              <circle cx="500" cy="120" r="25" fill="#0b1120" stroke={selectedNodeId === 'CbmPredictiveAlert' ? '#ff4da6' : '#39ff7a'} strokeWidth="2" />
              <text x="500" y="123" textAnchor="middle" fill="#dceeff" fontSize="9" fontWeight="bold">CBM Alert</text>
            </g>

            {/* AmisModelInference */}
            <g className="cursor-pointer" onClick={() => setSelectedNodeId('AmisModelInference')}>
              <circle cx="500" cy="280" r="25" fill="#0b1120" stroke={selectedNodeId === 'AmisModelInference' ? '#ff4da6' : '#c77dff'} strokeWidth="2" />
              <text x="500" y="283" textAnchor="middle" fill="#dceeff" fontSize="9" fontWeight="bold">Inference</text>
            </g>

            {/* SmeOverrideReport */}
            <g className="cursor-pointer" onClick={() => setSelectedNodeId('SmeOverrideReport')}>
              <circle cx="330" cy="320" r="25" fill="#0b1120" stroke={selectedNodeId === 'SmeOverrideReport' ? '#ff4da6' : '#ff4da6'} strokeWidth="2" />
              <text x="330" y="323" textAnchor="middle" fill="#dceeff" fontSize="9" fontWeight="bold">Override</text>
            </g>

            {/* CyberneticFeedbackLoop */}
            <g className="cursor-pointer" onClick={() => setSelectedNodeId('CyberneticFeedbackLoop')}>
              <circle cx="500" cy="380" r="25" fill="#0b1120" stroke={selectedNodeId === 'CyberneticFeedbackLoop' ? '#ff4da6' : '#ff4da6'} strokeWidth="2" />
              <text x="500" y="383" textAnchor="middle" fill="#dceeff" fontSize="9" fontWeight="bold">Loop</text>
            </g>
          </svg>
        </div>

        {/* NODE PROPERTY DRILL DOWN */}
        <div className="bg-amis-panel border border-amis-border rounded p-4 flex flex-col justify-between space-y-4">
          <div>
            <div className="text-xs font-bold text-amis-text-bright border-b border-amis-border pb-1.5 mb-3 flex justify-between">
              <span>Ontological Class Details</span>
              <span style={{ color: selectedNode.color }} className="font-mono">{selectedNode.id}</span>
            </div>

            <div className="space-y-4">
              <div>
                <span className="text-[10px] text-amis-text-dim block uppercase">owl:Class Identifier</span>
                <span className="text-xs text-amis-text-bright font-bold">{selectedNode.label}</span>
              </div>
              
              <div>
                <span className="text-[10px] text-amis-text-dim block uppercase">rdfs:comment (Definition)</span>
                <p className="text-xs text-amis-text leading-relaxed font-mono">
                  {selectedNode.comment}
                </p>
              </div>

              <div>
                <span className="text-[10px] text-amis-text-dim block uppercase">Semantic Properties</span>
                <div className="space-y-1 mt-1">
                  {selectedNode.properties.map((prop, i) => (
                    <div key={i} className="text-xs font-mono bg-amis-bg p-1 px-2 border border-amis-border/50 rounded text-amis-l1">
                      {prop}
                    </div>
                  ))}
                  {selectedNode.properties.length === 0 && (
                    <span className="text-xs text-amis-text-dim">No semantic data properties.</span>
                  )}
                </div>
              </div>
            </div>
          </div>

          <div className="border-t border-amis-border/50 pt-3 text-[10px] text-amis-text-dim font-mono leading-relaxed">
            💡 OWL class property restrictions establish the semantic boundaries. 
            For example, <code>SmeOverrideReport</code> maps human decisions directly to the <code>AmisModelInference</code> nodes.
          </div>
        </div>
      </div>
    </div>
  );
}
